[package]
name = "rust_lib_c_abi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"

[build-dependencies]
meson = "1.0.0"
cbindgen = "0.21.0"

[lib]
crate-type = ["cdylib"]