name: Build Workflows
on:
  workflow_call:
    inputs: 
      image_name:
        required: true
        type: string
      platform_name:
        required: true
        type: string
  
jobs:
  workflow_test:
    runs-on: ${{ inputs.image_name }}
    timeout-minutes: 10
    steps:
      - name: windows inspecton
        if: ${{ inputs.platform_name }} == 'windows'
        run: |
          Get-Childitem -Path D:\ -Include *clang* -File -Recurse
          Get-Childitem -Path D:\ -Include *llvm* -Recurse
          Get-Childitem -Path D:\ -Include *rustc* -File -Recurse
        shell: powershell
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: pip install
        timeout-minutes: 2
        run: pip3 install -r ${{ github.workspace }}/system_stuff/ci/requirements.txt
      - name: rust in cpp workflow
        working-directory: ${{ github.workspace }}/rust_in_cpp/rust_lib_cpp_bindings
        run: |
          meson setup --native-file ${{ github.workspace }}/system_stuff/ci/${{ inputs.platform_name }}/ci-native.ini rust_in_cpp_build
          meson compile -C rust_in_cpp_build
          meson test -C rust_in_cpp_build --print-errorlogs
          meson install -C rust_in_cpp_build  --destdir ./meson_install