name: PR Checks
on:
  pull_request:
    branches:
      - main
jobs:
  build-workflows-linux:
    uses: ./.github/workflows/build_workflows.yml
    with:
      image_name: ubuntu-latest
      platform_name: linux