name: PR Checks
on:
  pull_request:
    branches:
      - main
jobs:
  workflow_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: "find clang"
        run: find . -name 'clang*'
      - name: "find rustc"
        run: find . -name 'rustc'
      - name: pip install
        timeout-minutes: 2
        run: pip3 install -r system_stuff/ci/linux/requirements.txt