name: PR Checks
on:
  pull_request:
    branches:
      - main
jobs:
  build-workflows-windows:
    uses: ./.github/workflows/build_workflows.yml
    with:
      image_name: windows-latest
      platform_name: windows