name: PR Checks
on:
  pull_request:
    branches:
      - main
jobs:
  workflow_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: pip install
        timeout-minutes: 2
        run: pip3 install -r system_stuff/ci/linux/requirements.txt
      - name: rust in cpp workflow
        working-directory: ./rust_in_cpp/rust_lib_cpp_bindings
        run: |
          meson setup --native-file ./system_stuff/ci/linux/ci-native.ini rust_in_cpp_build
          meson compile -C rust_in_cpp_build
          meson test -C rust_in_cpp_build --print-errorlogs
          meson install -C rust_in_cpp_build  --destdir ./meson_install